---

- name: Setup gitlab_cli
  block:
    - ansible.builtin.include_tasks: install.yml
      when: gitlab_cli_install | bool

    - ansible.builtin.include_tasks: configure.yml
  tags:
    - role::gitlab_cli
    - role::gitlab_cli::install
    - role::gitlab_cli::configure
