---
# Role tasks

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 7
      fedora: 29
      rhel: 7

- include_role:
    name: amtega.packages
  vars:
    packages_os:
      centos:
        all:
          python-urllib3: present
      fedora:
        all:
          python2-urllib3: present
          python3-urllib3: present
      rhel:
        all:
          python-urllib3: present
    packages_python:
      all:
        all:
          "python-gitlab>=1.6": latest
          PyYaml: present

- block:
    - include_tasks: install.yml
    - include_tasks: configure.yml
  tags:
    - role::gitlab_cli
    - role::gitlab_cli::install
    - role::gitlab_cli::configure
